/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import dado.DadoClima;
import Observer.Observer;

import java.util.List;

/**
 *
 * @author kaios
 */
public class TelaDadosMedios extends javax.swing.JInternalFrame implements Observer {

    /**
     * Creates new form TelaDadosMedios
     */
    public TelaDadosMedios() {
        initComponents();
        setVisible(true);
    }
    @Override
    public void atualizar(List<DadoClima> TodosDados) {
        if(TodosDados.isEmpty()){
            infoPressao.setText(String.valueOf(0));
            infoRegistros.setText(String.valueOf(0));
            infoTemperatura.setText(String.valueOf(0));
            infoUmidade.setText(String.valueOf(0));

            return;
        }



        float somaTemperatura = 0;
        float somaUmidade = 0;
        float somaPressao = 0;

        for (DadoClima dado : TodosDados) {
            somaTemperatura += dado.getTemperatura();
            somaUmidade += dado.getUmidade();
            somaPressao += dado.getPressao();
        }

        int nRegistros = TodosDados.size();


        infoPressao.setText(String.valueOf(somaPressao/nRegistros));
        infoRegistros.setText(String.valueOf(nRegistros));
        infoTemperatura.setText(String.valueOf(somaTemperatura/nRegistros));
        infoUmidade.setText(String.valueOf(somaUmidade/nRegistros));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        infoRegistros = new javax.swing.JLabel();
        infoTemperatura = new javax.swing.JLabel();
        infoUmidade = new javax.swing.JLabel();
        infoPressao = new javax.swing.JLabel();

        setIconifiable(true);
        setTitle("Dados Medios");

        jLabel1.setText("Numero de registros:");

        jLabel2.setText("Temperatura:");

        jLabel3.setText("Umidade:");

        jLabel4.setText("Pressão");

        infoRegistros.setText("0");

        infoTemperatura.setText("0");

        infoUmidade.setText("0");

        infoPressao.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(infoTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoPressao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoTemperatura)
                        .addGap(35, 35, 35)
                        .addComponent(infoUmidade)
                        .addGap(35, 35, 35)
                        .addComponent(infoPressao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoPressao;
    private javax.swing.JLabel infoRegistros;
    private javax.swing.JLabel infoTemperatura;
    private javax.swing.JLabel infoUmidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
