/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import dado.DadoClima;
import Observer.Observer;

import java.util.List;

/**
 *
 * @author kaios
 */
public class TelaUltimaATT extends javax.swing.JInternalFrame implements Observer {
    @Override
    public void atualizar(List<DadoClima> dadoClimaList) {
        if ((dadoClimaList.isEmpty())){
            infoData.setText(String.valueOf(0));
            infoTemperatura.setText(String.valueOf(0));
            infoPressao.setText(String.valueOf(0));
            infoUmidade.setText(String.valueOf(0));
            return;
        }
        DadoClima dadoF = dadoClimaList.get((dadoClimaList.size() - 1));
        infoData.setText(String.valueOf(dadoF.getData()));
        infoTemperatura.setText(String.valueOf(dadoF.getTemperatura()));
        infoPressao.setText(String.valueOf(dadoF.getPressao()));
        infoUmidade.setText(String.valueOf(dadoF.getUmidade()));



    }
    /**
     * Creates new form TelaUltimaATT
     */
    public TelaUltimaATT() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        infoData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        infoTemperatura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        infoUmidade = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        infoPressao = new javax.swing.JLabel();

        setIconifiable(true);
        setTitle("Ultima atualização do Tempo");

        jLabel1.setText("Data:");

        infoData.setText("0");

        jLabel2.setText("Temperatura:");

        infoTemperatura.setText("0");

        jLabel3.setText("Umidade:");

        infoUmidade.setText("0");

        jLabel4.setText("Pressão");

        infoPressao.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoData, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(infoTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoPressao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(infoTemperatura)
                        .addGap(35, 35, 35)
                        .addComponent(infoUmidade)
                        .addGap(35, 35, 35)
                        .addComponent(infoPressao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoData;
    private javax.swing.JLabel infoPressao;
    private javax.swing.JLabel infoTemperatura;
    private javax.swing.JLabel infoUmidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;


    // End of variables declaration//GEN-END:variables
}
