/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Presenter.EstacaoClimatica;
import dado.ConfigManager;
import dado.DadoClima;
import logging.JsonFileLogger;
import logging.Logger;
import logging.XmlFileLogger;
import Observer.Observer;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author kaios
 */
public class TelaRegistros extends javax.swing.JInternalFrame implements Observer {

    EstacaoClimatica estacaoClimatica;
    List<DadoClima> dadoClimaList;


    /**
     * Creates new form TelaRegistros
     */
    Logger logger;
    public TelaRegistros(EstacaoClimatica estacaoClimatica) {
        this.estacaoClimatica = estacaoClimatica;
        initComponents();
        setVisible(true);
    }
    @Override
    public void atualizar(List<DadoClima> dadoClimaList) {
        this.dadoClimaList = dadoClimaList;

        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        tblModel.setRowCount(0);
        for (DadoClima dado: dadoClimaList){
            String[] data = new String[]{String.valueOf(dado.getData()), String.valueOf(dado.getTemperatura()), String.valueOf(dado.getUmidade()), String.valueOf(dado.getPressao())};
            tblModel.addRow(data);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        RemoverButton = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Registros");
        setName("Registros"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Temperatura", "Umidade", "Pressão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        RemoverButton.setText("Remover");
        RemoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RemoverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoverButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRowCount() == 1){
            estacaoClimatica.removeDado(dadoClimaList.get(jTable1.getSelectedRow()));

        }else{
            if(jTable1.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Tabela ta Vazia");
            }else{
                JOptionPane.showMessageDialog(this, "Selecione uma linha ai meu bom");
            }
        }
        if(ConfigManager.getLogFormat() == "XML"){
            this.logger = new XmlFileLogger("log.xml");
        }else if(ConfigManager.getLogFormat() == "JSON"){
            this.logger = new JsonFileLogger("log.json");
        }
        logger.logOperacao("Remoção");



    }//GEN-LAST:event_RemoverButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RemoverButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
